[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
  TERM = "xterm"

  command = "npm uninstall -D netlify-plugin-cypress"
